CREATE TABLE `GPS_TRACKER_DATA` 
(
  `CLIENT_ID` varchar(40) NOT NULL,
  `LATITUDE` varchar(40) NOT NULL,
  `LONGITUDE` varchar(40) NOT NULL,    
  `LAST_UPDATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CLIENT_ID`)
)