CREATE TABLE `PARKING_SPOTS_DATA` (
  `PARKING_SPOTS_COUNT` int(11) NOT NULL,
  `TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
)

INSERT INTO `PARKING_SPOTS_DATA`(`PARKING_SPOTS_COUNT`) VALUES (1)